wandb:
  log: true
  dir: ./
  experiment_name: "28-2-2023"
  entity: ""
  project: "mvtrans"
  save_dir: ./
hyperparameters:
  seed: 1337
  loss_seg_mult: 1
train:
  epochs: 1
  classes: 2
  batch_size: 1
  num_workers: 8
optimize:
  optimizer: "Adam"
  lr: 0.003
model:
  selected: "MVNet"
  mvnet:
    parameters:
      stage1_scale: 4.0
      stage2_scale: 2.0
      stage3_scale: 1.0
      transformer: False
      view_count: 3
      resnet: 18
      ndepths: 8
      depth_min: 0.01
      depth_max: 10.0
datasets:
  selected: "NerfSynthetic"
  camera:
    fx: 1111
    fy: 1111
    px: 400
    py: 400
  todd:
    path: data/todd/
  nerf_synthetic:
    root: data/nerf_synthetic/lego
    train_share: 0.7
    val_share: 0.2
    test_share: 0.1
